spring.application.name=EJ

spring.datasource.url=jdbc:postgresql://localhost:5432/ejtour
spring.datasource.username=postgres
spring.datasource.password=@Jeanvictor20031
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8081

management.endpoints.web.exposure.include=mappings

# CORREÇÃO: Keycloak está na porta 8080, não 8081!
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ejtour
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/ejtour/protocol/openid-connect/certs