spring.application.name=EJ

# Configuração para PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ejtour
spring.datasource.username=postgres
spring.datasource.password=@Jeanvictor20031
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA      
spring.jpa.hibernate.ddl-auto=update

# Configuração do Servidor Web
server.port=8081

# Configurações de Atuadores
management.endpoints.web.exposure.include=mappings

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8080/realms/ejtour
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
